# Generated by Django 4.2.24 on 2025-09-09 23:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('raw_response', models.JSONField(default=dict)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('reasoning', models.CharField(blank=True, max_length=100)),
                ('is_preferred', models.BooleanField(default=False)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ai_services.aiquery')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_services.aiservice')),
            ],
            options={
                'verbose_name': 'AI Response',
                'verbose_name_plural': 'AI Responses',
                'db_table': 'ai_responses',
                'ordering': ['-is_preferred', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('latency_score', models.FloatField(default=0)),
                ('cost_efficiency', models.FloatField(default=0)),
                ('time_to_selection', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='responses.airesponse')),
            ],
            options={
                'verbose_name': 'Response Metrics',
                'verbose_name_plural': 'Response Metrics',
                'db_table': 'response_metrics',
            },
        ),
        migrations.CreateModel(
            name='ResponseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_prompt', models.TextField()),
                ('analysis_response', models.TextField()),
                ('selection_reasoning', models.TextField()),
                ('analysis_service', models.CharField(default='claude', max_length=50)),
                ('analysis_tokens_used', models.PositiveIntegerField(default=0)),
                ('analysis_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responses.airesponse')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ai_services.aiquery')),
            ],
            options={
                'verbose_name': 'Response Analysis',
                'verbose_name_plural': 'Response Analyses',
                'db_table': 'response_analyses',
            },
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['query', 'service'], name='ai_response_query_i_8b0ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['is_preferred', 'is_selected'], name='ai_response_is_pref_942c9b_idx'),
        ),
    ]
