# Generated by Django 4.2.24 on 2025-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
