# Generated by Django 4.2.24 on 2025-10-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_create_cost_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsemetrics',
            name='response',
        ),
        migrations.DeleteModel(
            name='ResponseAnalysis',
        ),
        migrations.DeleteModel(
            name='ResponseMetrics',
        ),
    ]
