# Generated by Django 4.2.24 on 2025-10-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claude_model',
            field=models.CharField(blank=True, default='claude-sonnet-4-5-20250929', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gemini_model',
            field=models.CharField(blank=True, default='models/gemini-flash-latest', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4o', max_length=100),
        ),
    ]
