# Generated by Django 4.2.24 on 2025-10-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auth_method_user_google_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('passcode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email Passcode',
                'verbose_name_plural': 'Email Passcodes',
                'db_table': 'email_passcodes',
                'indexes': [models.Index(fields=['email', 'is_used'], name='email_passc_email_4520f2_idx'), models.Index(fields=['expires_at'], name='email_passc_expires_11fff0_idx')],
            },
        ),
    ]
