services:
  - type: web
    name: aix-api
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    preDeployCommand: python manage.py migrate
    dockerCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ENABLE_TEST_AI_ENDPOINTS
        value: "False"
      - key: USE_SQLITE
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        fromDatabase:
          name: aix-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: aix-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: aix-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: aix-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: aix-db
          property: port
      - key: REDIS_URL
        value: YOUR_REDIS_URL
      - key: CLAUDE_API_KEY
        value: YOUR_CLAUDE_API_KEY
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
      - key: GEMINI_API_KEY
        value: YOUR_GEMINI_API_KEY
      - key: REKA_API_KEY
        value: YOUR_REKA_API_KEY
      - key: GOOGLE_CSE_API_KEY
        value: YOUR_GOOGLE_CSE_API_KEY
      - key: GOOGLE_CSE_CX
        value: YOUR_GOOGLE_CSE_CX
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: YOUR_GOOGLE_OAUTH_CLIENT_ID
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        value: YOUR_GOOGLE_OAUTH_CLIENT_SECRET
  - type: worker
    name: aix-celery-worker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: celery -A config worker --loglevel=info
    envVars:
      - key: SECRET_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: SECRET_KEY
      - key: ENCRYPTION_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: ENCRYPTION_KEY
      - key: DEBUG
        value: "False"
      - key: ENABLE_TEST_AI_ENDPOINTS
        value: "False"
      - key: USE_SQLITE
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DB_NAME
        fromDatabase:
          name: aix-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: aix-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: aix-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: aix-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: aix-db
          property: port
      - key: REDIS_URL
        fromService:
          type: web
          name: aix-api
          envVarKey: REDIS_URL
      - key: CLAUDE_API_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: CLAUDE_API_KEY
      - key: OPENAI_API_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: OPENAI_API_KEY
      - key: GEMINI_API_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: GEMINI_API_KEY
      - key: REKA_API_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: REKA_API_KEY
      - key: GOOGLE_CSE_API_KEY
        fromService:
          type: web
          name: aix-api
          envVarKey: GOOGLE_CSE_API_KEY
      - key: GOOGLE_CSE_CX
        fromService:
          type: web
          name: aix-api
          envVarKey: GOOGLE_CSE_CX
      - key: GOOGLE_OAUTH_CLIENT_ID
        fromService:
          type: web
          name: aix-api
          envVarKey: GOOGLE_OAUTH_CLIENT_ID
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        fromService:
          type: web
          name: aix-api
          envVarKey: GOOGLE_OAUTH_CLIENT_SECRET
  - type: web
    name: aix-frontend
    env: static
    buildCommand: npm install --prefix frontend/frontend && npm run build --prefix frontend/frontend
    staticPublishPath: frontend/frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://aix-api.onrender.com
      - key: REACT_APP_WS_BASE_URL
        value: wss://aix-api.onrender.com
databases:
  - name: aix-db
    databaseName: chatai_db
    plan: free
