# Generated by Django 4.2.24 on 2025-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_mode',
            field=models.CharField(choices=[('standard', 'Standard Chat'), ('agent', 'LangChain Agent with Tools'), ('structured', 'Structured Summary Mode')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='enabled_tools',
            field=models.JSONField(default=list, help_text='List of enabled tool names for agent mode'),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional metadata like agent processing info, tools used, etc.'),
        ),
    ]
