# Generated by Django 4.2.24 on 2025-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_agent_mode_conversation_enabled_tools_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='enabled_tools',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether conversation is archived'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last message', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_user_message_excerpt',
            field=models.CharField(blank=True, help_text='Excerpt of last user message for preview', max_length=200),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Total cost of this conversation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional metadata like processing info, etc.'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conv_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-created_at'], name='conv_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_active'], name='conv_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'is_archived'], name='conv_user_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-total_cost'], name='conv_cost_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-total_tokens_used'], name='conv_tokens_idx'),
        ),
    ]
